### ISSUE TITLE
Initial mu differs from recommendation

### ISSUE THREAD

**Issue by egione** [dganguli/robust-pca#7]
You have:

  self.mu = np.prod(self.D.shape) / (4 * self.frobenius_norm(self.D))

wherein forbenius_norm computes the 2-norm. However in the RobustPCA paper, we have the recommendation:

  μ = n1 * n2 / 4 * |M|

"as suggested in Yuan and Yang", where |M| is the 1-norm of M. I suspect that parentheses have been omitted, and this is instead supposed to read:

  μ = n1 * n2 / (4 * |M|)

However, even imputing (as you did) the missing parentheses, the norm should be of order 1, not order 2.

**Comment by dganguli** [comment]
Thank you -- this is indeed a bug. It has been fixed. In my experiments, the precise choice of frobenius versus L1 norm for this computation didn't change results.

**Comment by sbrugman** [comment]
Came across this implementation since last using it a while back. Back then, the example didn't seem to converge nicely with the default parameters for a slightly different values for `N`, `num_groups`, `num_values_per_group` and `p_missing`.

For future reference, this was the effect of the μ parameter on the convergence (N = 1000, num_groups = 5, num_values_per_group = 100, p_missing = 0.05):
![image](https://user-images.githubusercontent.com/9756388/88304790-00338e80-cd09-11ea-970a-6a968e084151.png)
